# SwiftLint Configuration for Menu-Whisper

# Paths to include/exclude
included:
  - Sources
  - Tests

excluded:
  - Pods
  - .build
  - DerivedData

# Rules configuration
disabled_rules:
  - trailing_comma
  - todo
  - force_cast
  - force_try

opt_in_rules:
  - empty_count
  - empty_string
  - contains_over_first_not_nil
  - closure_spacing
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - switch_case_alignment
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Line length
line_length:
  warning: 120
  error: 140

# File length
file_length:
  warning: 500
  error: 800

# Function length
function_body_length:
  warning: 50
  error: 100

# Type body length
type_body_length:
  warning: 300
  error: 400

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 10
  error: 20

# Nesting depth
nesting:
  type_level: 3
  statement_level: 5

# Large tuple
large_tuple:
  warning: 3
  error: 4

# Identifier names
identifier_name:
  min_length:
    warning: 2
  excluded:
    - id
    - URL
    - url
    - x
    - y
    - z

# Custom rules
custom_rules:
  no_print:
    name: "No Print Statements"
    regex: "print\\("
    message: "Use Logger instead of print statements"
    severity: warning

reporter: "xcode"